### ISSUE TITLE
Although I have downloaded the file locally and placed it in the folders directory, I will still download it, and

### ISSUE THREAD

**Issue by guoyouworld** [KohakuBlueleaf/z-a1111-sd-webui-dtg#6]
Although I have downloaded the file locally and placed it in the folders directory, I still try to download it and it may fail to do so

G:\stable-diffusion\sd-webui-aki-v4.5\extensions\z-a1111-sd-webui-dtg\models\ggml-model-f16.gguf

|2024-04-18 10:15:10|[TOPI-KGen]-INFO: Downloading gguf model from KBlueLeaf/DanTagGen-beta
*** Error running process: G:\stable-diffusion\sd-webui-aki-v4.5\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py
    Traceback (most recent call last):
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
        conn = connection.create_connection(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
        raise err
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
        sock.connect(sa)
    TimeoutError: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
        httplib_response = self._make_request(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
        self._validate_conn(conn)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
        conn.connect()
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connection.py", line 363, in connect
        self.sock = conn = self._new_conn()
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
        raise ConnectTimeoutError(
    urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001902C53FEB0>, 'Connection to huggingface.co timed out. (connect timeout=10)')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\requests\adapters.py", line 486, in send
        resp = conn.urlopen(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
        retries = retries.increment(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /KBlueLeaf/DanTagGen-beta/resolve/main/ggml-model-f16.gguf (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001902C53FEB0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
        metadata = get_hf_file_metadata(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
        r = _request_wrapper(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
        response = _request_wrapper(
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
        response = get_session().request(method=method, url=url, **params)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\requests\sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\requests\sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
        return super().send(request, *args, **kwargs)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\requests\adapters.py", line 507, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /KBlueLeaf/DanTagGen-beta/resolve/main/ggml-model-f16.gguf (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001902C53FEB0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: b9fa7564-5e40-4b21-ad58-de2ab7acd68f)')

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "G:\stable-diffusion\sd-webui-aki-v4.5\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 304, in process
        self._process(prompt, aspect_ratio, seed + sub_seed, *args)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 365, in _process
        models.download_gguf(model_name, gguf_name)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\kgen\models.py", line 36, in download_gguf
        result = hf_hub_download(
      File "<enhanced_experience patches.hfmirror.huggingface_hub>", line 52, in hf_hub_download_wrapper_inner
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "G:\stable-diffusion\sd-webui-aki-v4.5\python\lib\site-packages\huggingface_hub\file_download.py", line 1371, in hf_hub_download
        raise LocalEntryNotFoundError(
    huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by KohakuBlueleaf** [comment]
I update the whole file system, if you want to download gguf by yourself.
You need to rename it to
```
<Model Name>_<gguf name>
```

For example:
```
DanTagGen-gamma_ggml-model-Q6_K.gguf
```

**Comment by guoyouworld** [comment]
Thank you very much, it's working now.
